anisopsblas:
	ln -s /home/it4i-fdurast/polynomialsmoothers/anisotropy/runs/anisopsblas anisopsblas
	ln -s /home/it4i-fdurast/polynomialsmoothers/anisotropy/runs/anisopsblascuda anisopsblascuda

clean:
	rm anisopsblas
	rm anisopsblascuda
	rm *.out
