anisopsblas:
	ln -s  /home/cirdan/Documenti/Paper/ParallelSmoothers/polynomialsmoothers/anisotropy/runs/anisopsblas anisopsblas
	ln -s  /home/cirdan/Documenti/Paper/ParallelSmoothers/polynomialsmoothers/anisotropy/runs/anisopsblascuda anisopsblascuda
clean:
	rm anisopsblas
	rm anisopsblascuda

