anisopsblas:
	ln -s /home/fdurastante/polynomialsmoothers/anisotropy/runs/anisopsblas anisopsblas
	ln -s /home/fdurastante/polynomialsmoothers/anisotropy/runs/anisopsblascuda anisopsblascuda
run_soc1:
	./run_cheby4_soc1_l1jacoby.sh
	./run_optcheby1_soc1_l1jacoby.sh 
	./run_optcheby4_soc1_l1jacoby.sh
clean:
	rm anisopsblas

